### PR TITLE
Sample files for Concert uploads

### PR DESCRIPTION
**Pull request by js-sravan**
Sample files to upload to Concert Application

### CODE REVIEW

**Review by SubruSK — COMMENTED** [review]
It will be better to have a folder structure.

concert-sample-data --> certificates
concert-sample-data --> vulnerabilities

**Review by SubruSK — APPROVED** [review]
Approved

**Comment by Ashwin-Goyal-AI** [comment]
Please use a fork off of main rather than a branch @mrsravanjs, thanks!

**Comment by js-sravan** [comment]
> Please use a fork off of main rather than a branch @mrsravanjs, thanks!

Noted @ashwingoyal273

**Comment by js-sravan** [comment]
Another PR is created from forked repo. So closing this PR

**Pull request closed without merging**
